# name: 'Skip Vercel Checks'
# on:
#   pull_request:
#     branches:
#       - 'gtmq_*'
#       - 'greg/**'
#
# jobs:
#   vercel_checks:
#     name: Vercel Preview Comments
#     runs-on: ubuntu-latest
#     steps:
#       - name: Skip Vercel Preview Comments
#         run: echo "Skipping Vercel Preview Comments for gtmq_"

  # vercel:
  #   name: UI Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Skip Vercel UI Tests
  #       run: echo "Skipping Vercel UI Tests for gtmq_"
